### ISSUE TITLE
Failed to download plugin

### ISSUE THREAD

**Issue by Bukashk0zzz** [GiGInnovationLabs/traefikgeoip2#13]
Getting this error when I try to use this plugin:

Plugins are disabled because an error has occurred." error="failed to download plugin github.com/GiGInnovationLabs/traefikgeoip2: failed to call service: Get \"https://plugins.traefik.io/public/download/github.com/GiGInnovationLabs/traefikgeoip2/v5.0.1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

I saw that you had the same issue before https://community.traefik.io/t/how-to-import-plugin-that-uses-unsafe-package/11186/8
Look like it persists again :(

**Comment by Bukashk0zzz** [comment]
Maybe there is a way to build Traefik with your plugin and not download it in runtime?

**Comment by eshepelyuk** [comment]
Hello

1. use local plugins, https://traefik.io/blog/using-private-plugins-in-traefik-proxy-2-5/
2. report to traefik, not here.

**Comment by Bukashk0zzz** [comment]
Understood. Thanks.

**Comment by Bukashk0zzz** [comment]
Created post on Traefik community https://community.traefik.io/t/failed-to-download-plugin/17155
