### ISSUE TITLE
Create MaxMind plugin for Traefik

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [GiGInnovationLabs/traefikgeoip2#8]

**Comment by fairok** [comment]
Is there any guide to install this plugin on K3S?

**Comment by ievgenii-shepeliuk** [comment]
> Is there any guide to install this plugin on K3S?

Not at the moment, unfortunately. 
But if you have some particular question - let me know, so I'll try to help.

**Comment by fairok** [comment]
> > Is there any guide to install this plugin on K3S?
> 
> Not at the moment, unfortunately. But if you have some particular question - let me know, so I'll try to help.

Not any more, thank you very much.
